### PR TITLE
Trial Run

### PR DESCRIPTION
**Pull request by B-Dionysus**
Added Staff (and URLs) to Black Knight, changed layout for company, added Stacey & Gary to company page.

### CODE REVIEW

**Comment by j1mc** [comment]
Thanks, Benjamin!  I'll get a look at this tonight.

**Comment by j1mc** [comment]
Hey Benjamin - nice work!  For the placeholder photos on the about page, could you make them the same size as the other images?

**Comment by B-Dionysus** [comment]
I'm confused. I pushed the image size fix to git, and then I think I merged
that branch with the about-fix branch? I'm a little unclear about what
happened, actually...

----
Benjamin Dionysus  (he/him/his)
Program Assistant, Cognitive Science Program
Northwestern University
847-467-2035

**Comment by j1mc** [comment]
Hi Benjamin - yes, it looks like you've merged this into the master branch!  Ooops / Yeay.  You can get a look at the site at https://staging.accidentalshakespeare.com/ to see how the changes look online. If you lik them, we can merge this change into the "live" branch, and it will automatically go to the regular site.

**Comment by B-Dionysus** [comment]
<grumble grumble> Sorry about that!

But yeah, I think this all looks good!

----
Benjamin Dionysus  (he/him/his)
Program Assistant, Cognitive Science Program
Northwestern University
847-467-2035

**Pull request merged**
