### PR TITLE
Image resize

### PR DESCRIPTION
**Pull request by hollabaq86**
I resized the remaining images so that the slideshows are all uniform (950 x 675 pixels). Additionally, I made an edit to the upcoming show file so that the website includes punctuation (Love's Labour's Lost).

### CODE REVIEW

**Comment by gorajski** [comment]
Please address these comments and let me know when done:

- In `productions/tempest_2013`, the image links are broken because the browser does not equate lowercase `.jpg` with uppercase `.JPG`.  For consistency's sake, we've been using `.JPG` in our file names, so please rename your image files to use `.JPG` as their extension.
- Since you're updating the punctuation for Love's Labour's Lost, could you also update it in `/past-productions` and `/productions/love_labours_lost_2012`?

Otherwise, looks good!

**Comment by hollabaq86** [comment]
Per Nick's feedback, I went through the project and normalized JPG naming conventions for all images.  This also helped me find a glitch with one production of Overruled that wasn't displaying images, those images are now resized and should be displaying.

**Comment by hollabaq86** [comment]
discovered why half the files were still not showing up with uppercase .JPG naming, this should now have all images showing with uppercase.  I also discovered a few production pages with wrong indentations that led to their images not generating, so I fixed that as well.  Finally, I went through all the html to make sure any image url path referenced uppercase .JPG

**Comment by gorajski** [comment]
It's looking better Holly.  Most of the images are showing correctly now.  Just a few fixes away:
1. In `productions/macbeth_2014/`, the `/assets/images/Rally.JPG` link is broken.  The image is currently named `/assets/images/rally.jpg`.
2. There is an extra image in `productions/overruled_092014/`.  This image, `/assets/images/Overruledposter_Remount_2b.JPG`, pertains instead to `productions/overruled_042014/`.  So you can either delete this image and reference entirely, or move it to `productions/overruled_042014/`.
3. None of the images in Much Ado About Nothing are showing.

**Comment by hollabaq86** [comment]
ok, I think I've got everything now.  Thanks for scouring over this PR with a fine tooth comb!  I really appreciate it.

**Pull request merged**
