### PR TITLE
added reverse sort, relabeled dates to dates_string, added date to co…

### PR DESCRIPTION
**Pull request by jepetersohn**
…llection as key

### CODE REVIEW

**Comment by TylerSmall19** [comment]
This doesn't seem to have changed anything in staging, despite clearly deploying. What's the URL for the page you changed? Can you confirm if the changes made it to staging? http://stagingshakes.s3-website.us-east-2.amazonaws.com

**Comment by j1mc** [comment]
Similar to what @TylerSmall19 noted, I'm not seeing the issue as being fully resolved yet, either. Even running a local copy of the branch doesn't show the events in reverse chronological order yet. It looks like this will require more work.

**Comment by hollabaq86** [comment]
I pulled down Joan's request and past productions are appearing in order from most recent -> oldest

screen shot 2017-03-21 at 5 45 33 pm

**Comment by hollabaq86** [comment]
@TylerSmall19 @j1mc Joan's code is showing productions in order on my local server, I'm going to go ahead and merge this request so that Nick G and Mhar have updated Masters to work from. Not sure why it's not updating to staging...

**Pull request merged**
